version: "3"

services:
  rabbitmq:
    image: "rabbitmq:latest"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:15672"]
        interval: 30s
        timeout: 10s
        retries: 5
  library:
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    restart: on-failure    
    environment:
      CLOUD_FILE: /app/local.yml
    build:
      context: ../
      dockerfile: docker/Dockerfile.test
