FROM golang:1.12.5-stretch as builder
LABEL maintainer="andy.lo-a-foe@philips.com"
WORKDIR /build
COPY go.mod .
COPY go.sum .

# Get dependancies - will also be cached if we won't change mod/sum
RUN go mod download

# Build
COPY . .
RUN go build test_app/main.go

WORKDIR /app/
COPY /docker/local.yml /app/local.yml
COPY /docker/wait-for-it.sh /app

WORKDIR /build
ENTRYPOINT ["/app/wait-for-it.sh", "rabbitmq:5672","--","go", "test", "./..."]
