FROM golang:1.12.5-stretch as builder
LABEL maintainer="andy.lo-a-foe@philips.com"
WORKDIR /build
COPY go.mod .
COPY go.sum .

# Get dependancies - will also be cached if we won't change mod/sum
RUN go mod download

# Build
COPY . .
RUN go build -o main test_app/main.go

FROM golang:1.12.5-stretch
WORKDIR /app/
COPY --from=builder /build/main /app
COPY --from=builder /build/docker/local.yml /app/local.yml
COPY --from=builder /build/docker/wait-for-it.sh /app
ENTRYPOINT ["/app/wait-for-it.sh", "rabbitmq:5672","--","/app/main"]
